plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java.srcDirs = []
        kotlin.srcDirs = ['src/logic/kotlin']
        resources.srcDirs = []
    }
    test {
        java.srcDirs = []
        kotlin.srcDirs = ['src/test/kotlin']
        resources.srcDirs = []
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
}

tasks.named('jar') {
    enabled = false
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
        exceptionFormat 'full'
    }
}
