package com.hamsterscreate.compat.config

import com.hamsterscreate.compat.logic.WheelKinetics
import net.minecraftforge.common.ForgeConfigSpec

object CompatServerConfig {
    @JvmField
    val SPEC: ForgeConfigSpec

    @JvmField
    val HAMSTER_EXITS_WHEEL_ON_ITS_OWN: ForgeConfigSpec.BooleanValue

    @JvmField
    val GENERATED_RPM: ForgeConfigSpec.IntValue

    @JvmField
    val STRESS_CAPACITY_PER_RPM: ForgeConfigSpec.DoubleValue

    init {
        val builder = ForgeConfigSpec.Builder()
        builder.push("hamster_wheel")

        HAMSTER_EXITS_WHEEL_ON_ITS_OWN = builder
            .comment(
                "If true, hamsters can leave the wheel on their own (Hamsters default).",
                "If false, they stay until a player right-clicks the wheel.",
                "Если true, хомяк может сам выйти из колеса (как в Hamsters).",
                "Если false, хомяк остаётся, пока игрок не заберёт его ПКМ."
            )
            .define("hamsterExitsWheelOnItsOwn", false)

        GENERATED_RPM = builder
            .comment(
                "RPM generated by one hamster, matching the Create hand crank by default (32).",
                "Обороты в минуту от одного хомяка. По умолчанию как у ручки Create (32)."
            )
            .defineInRange("generatedRpm", WheelKinetics.HAND_CRANK_RPM, 1, 256)

        STRESS_CAPACITY_PER_RPM = builder
            .comment(
                "Stress capacity per RPM. Hand crank default is 8 SU/RPM (256 SU at 32 RPM).",
                "Ёмкость стресса на 1 RPM. У ручки Create это 8 SU/RPM (256 SU при 32 RPM)."
            )
            .defineInRange("stressCapacityPerRpm", WheelKinetics.HAND_CRANK_SU_PER_RPM, 0.0, 16384.0)

        builder.pop()
        SPEC = builder.build()
    }

    @JvmStatic
    fun hamsterExitsWheelOnItsOwn(): Boolean = HAMSTER_EXITS_WHEEL_ON_ITS_OWN.get()

    @JvmStatic
    fun generatedRpm(): Int = GENERATED_RPM.get()

    @JvmStatic
    fun stressCapacityPerRpm(): Double = STRESS_CAPACITY_PER_RPM.get()
}
